services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.python
    env_file:
      - ../.env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "5173:80"
    depends_on:
      - api
